{"uid":"74b109e582a2f6af","name":"test_mongos_tls_ca_mismatch","fullName":"tests.integration.tls_tests.test_tls#test_mongos_tls_ca_mismatch","historyId":"c4fea09c832c303e15134970a2c845b1","time":{"start":1724120292994,"stop":1724120730383,"duration":437389},"description":"Tests that mongos charm can disable TLS.","descriptionHtml":"<p>Tests that mongos charm can disable TLS.</p>\n","status":"failed","statusMessage":"AssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 848, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 879, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/mongos-operator/mongos-operator/tests/integration/tls_tests/test_tls.py\", line 124, in test_mongos_tls_ca_mismatch\n    assert (\nAssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","flaky":true,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1724117240858,"stop":1724117240859,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1724117240859,"stop":1724117240859,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1724117240859,"stop":1724117241021,"duration":162},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1724120292994,"stop":1724120292994,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Tests that mongos charm can disable TLS.","status":"failed","statusMessage":"AssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 848, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 879, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/mongos-operator/mongos-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/mongos-operator/mongos-operator/tests/integration/tls_tests/test_tls.py\", line 124, in test_mongos_tls_ca_mismatch\n    assert (\nAssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","steps":[],"attachments":[{"uid":"3055b3ffd9646af9","name":"log","source":"3055b3ffd9646af9.txt","type":"text/plain","size":14436}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1724120730387,"stop":1724120730387,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1724120730388,"stop":1724120730730,"duration":342},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1724120730731,"stop":1724120730731,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1724120730731,"stop":1724120730731,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1724120730731,"stop":1724120730731,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.tls_tests"},{"name":"suite","value":"test_tls"},{"name":"host","value":"fv-az1433-839"},{"name":"thread","value":"8579-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.tls_tests.test_tls"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"ce541a7fc6efdfbc","status":"unknown","time":{}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":6,"broken":0,"skipped":0,"passed":2,"unknown":0,"total":8},"items":[{"uid":"ff277ce2696a8241","reportUrl":"../383//#testresult/ff277ce2696a8241","status":"failed","statusDetails":"AssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","time":{"start":1724033945496,"stop":1724034386376,"duration":440880}},{"uid":"1191ec30a0165e6e","reportUrl":"../382//#testresult/1191ec30a0165e6e","status":"passed","time":{"start":1723947457600,"stop":1723947897229,"duration":439629}},{"uid":"1b1faa3720b87ebb","reportUrl":"../381//#testresult/1b1faa3720b87ebb","status":"passed","time":{"start":1723860884623,"stop":1723861340250,"duration":455627}},{"uid":"a28c2371d44cd448","reportUrl":"../378//#testresult/a28c2371d44cd448","status":"failed","statusDetails":"AssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","time":{"start":1723774649221,"stop":1723775086957,"duration":437736}},{"uid":"f7cf1b4299ac5696","reportUrl":"../377//#testresult/f7cf1b4299ac5696","status":"failed","statusDetails":"AssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","time":{"start":1723688271471,"stop":1723688713038,"duration":441567}},{"uid":"68222fb9c6ae7517","reportUrl":"../375//#testresult/68222fb9c6ae7517","status":"failed","statusDetails":"AssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","time":{"start":1723602105511,"stop":1723602542319,"duration":436808}},{"uid":"310da08cfd3c3265","reportUrl":"../371//#testresult/310da08cfd3c3265","status":"failed","statusDetails":"AssertionError: mongos fails to report mismatch in CA.\nassert 'Waiting for MongoDB to start' == \"mongos CA an... don't match.\"\n  \n  - mongos CA and Config-Server CA don't match.\n  + Waiting for MongoDB to start","time":{"start":1723516254070,"stop":1723516692625,"duration":438555}}]},"tags":["asyncio","abort_on_fail","group(1)"]},"source":"74b109e582a2f6af.json","parameterValues":[]}